In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('finetune_data/processed_data/base_dataset.csv')
df_vali = df[df['split'] == 'validation']
df_vali

,id,split,protein_path,ligand_path,standardize_smi,pocket_vec,evo_vec,ifp,ligand_vec
688796,val_0,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,COc1ccc(S(=O)(=O)N2CCN(Cc3ccccc3)C(=O)CC2C(O)=...,NaN,NaN,NaN,NaN
688797,val_1,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,CCCc1nc(CC)c(C(=O)OCc2cccc(C(=O)c3ccccc3)c2)n1...,NaN,NaN,NaN,NaN
688798,val_2,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,O=C1NN(c2ccccc2)C(=O)/C1=C/c1cccc(OCc2cccc(C(F...,NaN,NaN,NaN,NaN
688799,val_3,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,CN1CCc2nc(C(=O)N[C@@H]3CC(C(=O)N(C)C)CCC3NC(=O...,NaN,NaN,NaN,NaN
688800,val_4,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,Cc1ccnc(CCc2cccc([C@H](N)Cc3cc(C)cc(=N)[nH]3)c...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
689791,val_995,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,O=C(NCCCCC(CO)NC(=O)c1cccc(O)c1O)c1cccc(O)c1O,NaN,NaN,NaN,NaN
689792,val_996,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,CCN(Cc1ccc2[nH]cnc2c1Cl)c1nc(=Nc2cc(C3CC3)[nH]...,NaN,NaN,NaN,NaN
689793,val_997,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,c1cn2c(NCCN3CCOCC3)c(-c3ccc4nccn4c3)nc2cn1,NaN,NaN,NaN,NaN
689794,val_998,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,CN1CC[C@@]2(C)c3cc(OC(=O)Nc4ccccc4)ccc3N(C)[C@...,NaN,NaN,NaN,NaN
689795,val_999,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,CCOc1ccc(OC[C@@H](O)CN(C)Cc2c(C)nn(Cc3ccccc3Cl...,NaN,NaN,NaN,NaN

In [6]:
from src.eval.components.moses import SA, QED
from rdkit import Chem

In [8]:
df_vali['SA'] = df_vali['standardize_smi'].apply(lambda x: SA(Chem.MolFromSmiles(x)))
df_vali['QED'] = df_vali['standardize_smi'].apply(lambda x: QED(Chem.MolFromSmiles(x)))

print(df_vali['SA'].mean())
print(df_vali['QED'].mean())

3.119617233833337
0.5123665877750668

In [9]:
df_vali

,id,split,protein_path,ligand_path,standardize_smi,pocket_vec,evo_vec,ifp,ligand_vec,SA,QED
688796,val_0,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,COc1ccc(S(=O)(=O)N2CCN(Cc3ccccc3)C(=O)CC2C(O)=...,NaN,NaN,NaN,NaN,2.906258,0.310436
688797,val_1,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,CCCc1nc(CC)c(C(=O)OCc2cccc(C(=O)c3ccccc3)c2)n1...,NaN,NaN,NaN,NaN,3.137345,0.078624
688798,val_2,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,O=C1NN(c2ccccc2)C(=O)/C1=C/c1cccc(OCc2cccc(C(F...,NaN,NaN,NaN,NaN,2.310064,0.462300
688799,val_3,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,CN1CCc2nc(C(=O)N[C@@H]3CC(C(=O)N(C)C)CCC3NC(=O...,NaN,NaN,NaN,NaN,3.999697,0.424030
688800,val_4,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,Cc1ccnc(CCc2cccc([C@H](N)Cc3cc(C)cc(=N)[nH]3)c...,NaN,NaN,NaN,NaN,3.328654,0.638228
...,...,...,...,...,...,...,...,...,...,...,...
689791,val_995,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,O=C(NCCCCC(CO)NC(=O)c1cccc(O)c1O)c1cccc(O)c1O,NaN,NaN,NaN,NaN,2.830953,0.244154
689792,val_996,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,CCN(Cc1ccc2[nH]cnc2c1Cl)c1nc(=Nc2cc(C3CC3)[nH]...,NaN,NaN,NaN,NaN,3.750895,0.451229
689793,val_997,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,c1cn2c(NCCN3CCOCC3)c(-c3ccc4nccn4c3)nc2cn1,NaN,NaN,NaN,NaN,2.804078,0.582858
689794,val_998,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,CN1CC[C@@]2(C)c3cc(OC(=O)Nc4ccccc4)ccc3N(C)[C@...,NaN,NaN,NaN,NaN,3.131035,0.908131
689795,val_999,validation,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...,CCOc1ccc(OC[C@@H](O)CN(C)Cc2c(C)nn(Cc3ccccc3Cl...,NaN,NaN,NaN,NaN,2.753913,0.459953