In [1]:
# 简单通用可视化（Jupyter 单元格）
from pathlib import Path
import pickle, math
import matplotlib.pyplot as plt

# 可选依赖按需导入（缺谁就 None）
try: import pandas as pd
except: pd = None
try: import numpy as np
except: np = None
try: import torch
except: torch = None

def viz_pkl(path):
    p = Path(path)
    with open(p, "rb") as f:
        obj = pickle.load(f)
    print(f"Loaded: {type(obj)}")

    # 1) pandas.DataFrame
    if pd is not None and isinstance(obj, pd.DataFrame):
        display(obj.head(10))
        num_cols = obj.select_dtypes(include="number").columns.tolist()
        if num_cols:
            n = len(num_cols); cols = min(3, n); rows = math.ceil(n/cols)
            plt.figure(figsize=(4*cols, 3*rows))
            for i, c in enumerate(num_cols, 1):
                plt.subplot(rows, cols, i); obj[c].dropna().hist(bins=30); plt.title(c)
            plt.tight_layout(); plt.show()
        return obj

    # 2) numpy.ndarray
    if np is not None and isinstance(obj, np.ndarray):
        print("shape:", obj.shape, "dtype:", obj.dtype)
        if obj.ndim == 1:
            plt.figure(figsize=(6,3)); plt.plot(obj); plt.title("1D array"); plt.show()
        elif obj.ndim == 2:
            plt.figure(figsize=(5,4)); plt.imshow(obj); plt.title("2D array"); plt.colorbar(); plt.show()
        return obj

    # 3) PyTorch: state_dict 或含 state_dict 的对象
    if torch is not None and (
        (isinstance(obj, dict) and any(hasattr(v, "shape") for v in obj.values()))
        or hasattr(obj, "state_dict")
    ):
        sd = obj if isinstance(obj, dict) else obj.state_dict()
        total = 0
        rows = []
        for k, v in sd.items():
            n = int(v.numel()) if hasattr(v, "numel") else 0
            total += n
            rows.append((k, n))
        print(f"Total params: {total:,}")
        rows.sort(key=lambda x: x[1], reverse=True)
        top = rows[:20]
        if top:
            plt.figure(figsize=(8, max(3, len(top)*0.3)))
            plt.barh([k for k,_ in top][::-1], [n for _,n in top][::-1])
            plt.title("Top parameter counts"); plt.tight_layout(); plt.show()
        return obj

    # 4) dict / list：尝试转 DataFrame，否则打印摘要
    if isinstance(obj, (dict, list)):
        if pd is not None:
            try:
                df = pd.DataFrame(obj)
                display(df.head(10))
                return obj
            except Exception:
                pass
        # 摘要打印
        if isinstance(obj, dict):
            print("dict keys (up to 30):", list(obj.keys())[:30])
        else:
            print("list length:", len(obj), "; first 5 types:", [type(x).__name__ for x in obj[:5]])
        return obj

    # 5) 其他类型：打印 repr 以便你后续决定怎么画
    print(repr(obj)[:1000])
    return obj

# 用法：把路径换成你的文件
# obj = viz_pkl("your_file.pkl")

In [3]:
obj = viz_pkl("finetune_data/protein_extraction_10.0A_index.pkl")

Loaded: <class 'list'>

,0,1
0,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
1,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
2,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
3,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
4,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
5,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
6,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
7,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
8,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
9,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...

In [4]:
obj
print(len(obj))

689796

In [5]:
obj[-1]

('/home/yang2531/Documents/Project/Structure_safe/finetune_data/low/target_CHEMBL5648/CHEMBL3644489/protein_10.0A.pdb',
 '/home/yang2531/Documents/Project/Structure_safe/finetune_data/low/target_CHEMBL5648/CHEMBL3644489/ligand.sdf')

In [6]:
obj[300000]

('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4409/CHEMBL1642582/protein_10.0A.pdb',
 '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4409/CHEMBL1642582/ligand.sdf')

In [2]:
obj_train = viz_pkl("finetune_data/training_set.pkl")
print(len(obj_train))
obj_train

Loaded: <class 'list'>

,0,1
0,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
1,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
2,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
3,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
4,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
5,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
6,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
7,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
8,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
9,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...

681700

[('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL369490/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL369490/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL1276446/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL1276446/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4550/CHEMBL3780838/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4550/CHEMBL3780838/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL1774086/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL1774086/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL235/CHEMBL340011/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL235/CHEMBL340011/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5888/CHEMBL3692438/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5888/CHEMBL3692438/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL4782149/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL4782149/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL137953/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL137953/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4462/CHEMBL596655/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4462/CHEMBL596655/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL3669112/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL3669112/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3577/CHEMBL3971230/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3577/CHEMBL3971230/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL194202/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL194202/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2034/CHEMBL3126950/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2034/CHEMBL3126950/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3160/CHEMBL161033/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3160/CHEMBL161033/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL3109764/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL3109764/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL1971943/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL1971943/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL4564272/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL4564272/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4550/CHEMBL3683275/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4550/CHEMBL3683275/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL3676863/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL3676863/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL235/CHEMBL221342/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL235/CHEMBL221342/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5888/CHEMBL3700263/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5888/CHEMBL3700263/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL1957812/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL1957812/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4462/CHEMBL3804891/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4462/CHEMBL3804891/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL3946399/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL3946399/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3577/CHEMBL4206667/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3577/CHEMBL4206667/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL1621/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL1621/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL4869556/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL4869556/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2034/CHEMBL363179/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2034/CHEMBL363179/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3160/CHEMBL35926/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3160/CHEMBL35926/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL252878/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL252878/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL2037226/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL2037226/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4550/CHEMBL3678493/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4550/CHEMBL3678493/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL5199780/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL5199780/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL235/CHEMBL5084763/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL235/CHEMBL5084763/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5888/CHEMBL4110441/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5888/CHEMBL4110441/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL440389/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL440389/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4462/CHEMBL4861333/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4462/CHEMBL4861333/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL570198/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL570198/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3577/CHEMBL4209599/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3577/CHEMBL4209599/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL3642806/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL3642806/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2034/CHEMBL4086436/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2034/CHEMBL4086436/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3160/CHEMBL328247/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3160/CHEMBL328247/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL3354406/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL3354406/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL3184679/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL3184679/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4550/CHEMBL3684745/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4550/CHEMBL3684745/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL3971383/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL3971383/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL235/CHEMBL201832/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL235/CHEMBL201832/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5888/CHEMBL3696612/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5888/CHEMBL3696612/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL127257/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL127257/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4462/CHEMBL3358385/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4462/CHEMBL3358385/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL2180208/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL2180208/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3577/CHEMBL4648730/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3577/CHEMBL4648730/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL7568/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL7568/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2034/CHEMBL3358946/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2034/CHEMBL3358946/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3160/CHEMBL341334/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3160/CHEMBL341334/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL410677/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL410677/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL212269/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL212269/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4550/CHEMBL610472/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4550/CHEMBL610472/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL2107510/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL2107510/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL235/CHEMBL2206305/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL235/CHEMBL2206305/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5888/CHEMBL4106917/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5888/CHEMBL4106917/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL1081644/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL1081644/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4462/CHEMBL4073924/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4462/CHEMBL4073924/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL3354965/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL3354965/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3577/CHEMBL4855040/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3577/CHEMBL4855040/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL46523/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL46523/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2034/CHEMBL397050/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2034/CHEMBL397050/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3160/CHEMBL104104/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3160/CHEMBL104104/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL2177263/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL2177263/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL272453/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2815/CHEMBL272453/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4550/CHEMBL3666958/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4550/CHEMBL3666958/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL4095562/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL4095562/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL235/CHEMBL4277858/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL235/CHEMBL4277858/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5888/CHEMBL3700244/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5888/CHEMBL3700244/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL4290309/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL4290309/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4462/CHEMBL3358391/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4462/CHEMBL3358391/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL583134/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL583134/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3577/CHEMBL4211406/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3577/CHEMBL4211406/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL1774077/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL224/CHEMBL1774077/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2034/CHEMBL81397/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2034/CHEMBL81397/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3160/CHEMBL1791078/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3160/CHEMBL1791078/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL253/CHEMBL3354944/protein_10.0A.pdb',

In [5]:
obj_test = viz_pkl("finetune_data/validation_set.pkl")
print(len(obj_test))
obj_test

Loaded: <class 'list'>

,0,1
0,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
1,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
2,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
3,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
4,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
5,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
6,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
7,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
8,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...
9,/home/yang2531/Documents/Project/Structure_saf...,/home/yang2531/Documents/Project/Structure_saf...

228

[('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3137292/CHEMBL3099405/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3137292/CHEMBL3099405/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL1930/CHEMBL4594145/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL1930/CHEMBL4594145/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL1926488/CHEMBL1926835/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL1926488/CHEMBL1926835/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL1075320/CHEMBL1084708/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL1075320/CHEMBL1084708/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3309008/CHEMBL46294/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3309008/CHEMBL46294/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2010635/CHEMBL2032134/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2010635/CHEMBL2032134/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3217378/CHEMBL44803/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3217378/CHEMBL44803/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3856166/CHEMBL4469438/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3856166/CHEMBL4469438/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5990/CHEMBL2017822/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5990/CHEMBL2017822/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2321639/CHEMBL2326313/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL2321639/CHEMBL2326313/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3580522/CHEMBL4578475/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3580522/CHEMBL4578475/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3879870/CHEMBL3931070/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3879870/CHEMBL3931070/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3309037/CHEMBL1214127/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3309037/CHEMBL1214127/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5526/CHEMBL199629/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5526/CHEMBL199629/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3596075/CHEMBL3629697/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3596075/CHEMBL3629697/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4603/CHEMBL205982/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4603/CHEMBL205982/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL1830/CHEMBL3193213/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL1830/CHEMBL3193213/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3179/CHEMBL310012/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3179/CHEMBL310012/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3562169/CHEMBL3577290/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL3562169/CHEMBL3577290/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4523175/CHEMBL4446301/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4523175/CHEMBL4446301/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4418/CHEMBL197951/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL4418/CHEMBL197951/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL1075080/CHEMBL4518887/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL1075080/CHEMBL4518887/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5027/CHEMBL181962/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5027/CHEMBL181962/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5174/CHEMBL4205347/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/moderate/target_CHEMBL5174/CHEMBL4205347/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4630879/CHEMBL4863322/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4630879/CHEMBL4863322/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4295585/CHEMBL4166160/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4295585/CHEMBL4166160/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4295572/CHEMBL1163085/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4295572/CHEMBL1163085/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL6111/CHEMBL5070220/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL6111/CHEMBL5070220/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4222/CHEMBL372524/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4222/CHEMBL372524/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3174/CHEMBL4593975/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3174/CHEMBL4593975/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3277/CHEMBL1213370/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3277/CHEMBL1213370/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL2285353/CHEMBL2289489/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL2285353/CHEMBL2289489/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1293295/CHEMBL1410015/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1293295/CHEMBL1410015/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4523260/CHEMBL411879/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4523260/CHEMBL411879/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4523342/CHEMBL4556129/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4523342/CHEMBL4556129/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4739843/CHEMBL5084938/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4739843/CHEMBL5084938/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3259512/CHEMBL3265226/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3259512/CHEMBL3265226/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL6000/CHEMBL5172767/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL6000/CHEMBL5172767/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3301560/CHEMBL322782/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3301560/CHEMBL322782/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4296290/CHEMBL1213019/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4296290/CHEMBL1213019/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL2311239/CHEMBL2312560/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL2311239/CHEMBL2312560/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3091/CHEMBL3098768/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3091/CHEMBL3098768/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL5348/CHEMBL4245260/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL5348/CHEMBL4245260/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL2010627/CHEMBL4099031/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL2010627/CHEMBL4099031/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4105798/CHEMBL4064985/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4105798/CHEMBL4064985/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4319/CHEMBL272818/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4319/CHEMBL272818/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4630854/CHEMBL4642700/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4630854/CHEMBL4642700/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3954/CHEMBL1161626/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3954/CHEMBL1161626/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4520/CHEMBL5193958/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4520/CHEMBL5193958/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3826862/CHEMBL3827395/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3826862/CHEMBL3827395/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4105809/CHEMBL4528101/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4105809/CHEMBL4528101/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3588737/CHEMBL4791017/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3588737/CHEMBL4791017/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3286061/CHEMBL3290335/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3286061/CHEMBL3290335/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1075024/CHEMBL244805/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1075024/CHEMBL244805/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL5523/CHEMBL3414622/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL5523/CHEMBL3414622/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL5225/CHEMBL158/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL5225/CHEMBL158/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3708265/CHEMBL4436749/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3708265/CHEMBL4436749/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1681614/CHEMBL402140/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1681614/CHEMBL402140/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1772929/CHEMBL2164318/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1772929/CHEMBL2164318/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4523510/CHEMBL5093928/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4523510/CHEMBL5093928/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4296293/CHEMBL1213398/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4296293/CHEMBL1213398/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1293287/CHEMBL4437643/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1293287/CHEMBL4437643/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1293277/CHEMBL3311372/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1293277/CHEMBL3311372/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4640/CHEMBL5169811/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4640/CHEMBL5169811/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL2706/CHEMBL3904357/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL2706/CHEMBL3904357/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1293275/CHEMBL4463681/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1293275/CHEMBL4463681/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3217379/CHEMBL1928286/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3217379/CHEMBL1928286/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL5169173/CHEMBL5193085/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL5169173/CHEMBL5193085/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3972/CHEMBL23278/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3972/CHEMBL23278/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3108647/CHEMBL5178972/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3108647/CHEMBL5178972/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1075165/CHEMBL3622372/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1075165/CHEMBL3622372/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4295631/CHEMBL1229798/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4295631/CHEMBL1229798/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1075026/CHEMBL857/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1075026/CHEMBL857/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL6070/CHEMBL379367/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL6070/CHEMBL379367/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3217380/CHEMBL3903683/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3217380/CHEMBL3903683/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL6124/CHEMBL505661/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL6124/CHEMBL505661/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3712868/CHEMBL4175585/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3712868/CHEMBL4175585/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4295703/CHEMBL4165503/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL4295703/CHEMBL4165503/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1908385/CHEMBL4162544/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL1908385/CHEMBL4162544/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3984/CHEMBL5190904/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3984/CHEMBL5190904/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL2064/CHEMBL2391908/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL2064/CHEMBL2391908/ligand.sdf'),
 ('/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3569/CHEMBL62855/protein_10.0A.pdb',
  '/home/yang2531/Documents/Project/Structure_safe/finetune_data/high/target_CHEMBL3569/CHEMBL62855/ligand.sdf'),

In [1]:
import torch

In [2]:
data = torch.load("finetune_data/processed_data/hf_bdnv2_dataset/ligand_stats.pt")
print(data)

{'mu': tensor([ 9.6470,  4.4209, -7.5277,  ..., 13.5078, 14.0191,  8.4731]), 'sigma': tensor([2.0966, 2.9303, 3.3899,  ..., 6.8708, 4.9199, 4.6296]), 'shape': torch.Size([689796, 1536]), 'num_samples': 689796, 'num_dims': 1536}

/tmp/ipykernel_108311/2760732191.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data = torch.load("finetune_data/processed_data/hf_bdnv2_dataset/ligand_stats.pt")

In [7]:
print(data['mu'].shape)
data['sigma'].shape

torch.Size([1536])

torch.Size([1536])